### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by Razdeep** [MadhavBahlMD/Control-Yourself#14]
Choose a LICENSE for this repository.

**Comment by MadhavBahlMD** [comment]
Yes, @Razdeep even I was thinking for the same from a couple of days, let's discuss on Gitter which license should we choose.

**Comment by MadhavBahlMD** [comment]
I was thinking of going with a General Public License. MIT is also good.

I will go through the list of all licenses and confirm which one to use.

**Comment by MadhavBahlMD** [comment]
@Razdeep I guess MIT  license would be fine, closing this issue
