### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [MadhavBahlMD/Control-Yourself#44]
Hey @MadhavBahlMD 

I designed a logo for the repo. I was inspired by the explanations in the readme file. The idea of the logo is also available in the below image. Please tell me what you think. Best regards.

![cont](https://user-images.githubusercontent.com/36298335/46910700-6e063000-cf51-11e8-9cff-4570f398b06c.jpg)

**Comment by MadhavBahlMD** [comment]
![image](https://user-images.githubusercontent.com/26179770/46913549-ae46cc00-cfac-11e8-9ed2-37c55c5ff0ef.png)

@reallinfo  These two look best :smiley: 

Can you add pngs for both of them in `logos` directory?

Also, if you can add the logo for all of them, it would be really great, that way I will be able to look up which one looks better.

Thanks alot for your contributions :heart:

**Comment by MadhavBahlMD** [comment]
Also, @reallinfo add your name in the contributors through all-contributors-cli

**Comment by reallinfo** [comment]
I think I have a better idea. The logo has become original in this way. Please check the idea :)

![cont](https://user-images.githubusercontent.com/36298335/46915263-bb19ee80-cfb1-11e8-8ac2-76df63a67fd1.jpg)

**Comment by MadhavBahlMD** [comment]
Amazing @reallinfo , this looks awesome :star2: 

This one is great, you can make a PR with all these PNGs in logos folder :)
